services:
  - type: web
    name: pepeleads2
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///survey_response.db
        sync: false
